In [1]:
import pandas as pd
import numpy as np


In [60]:
from sklearn.linear_model import LogisticRegressionCV,LinearRegression

In [19]:
df=pd.read_csv("Fin. Stats KTDK-2 - Fin. Stats.csv")

In [85]:
df

ID    ROA(A)    ROA(B)    ROA(C)  Operating Gross Margin  \
0      0  0.424389  0.405750  0.370594                0.601457   
1      1  0.538214  0.516730  0.464291                0.610235   
2      2  0.499019  0.472295  0.426071                0.601450   
3      3  0.451265  0.457733  0.399844                0.583541   
4      4  0.538432  0.522298  0.465022                0.598783   
..   ...       ...       ...       ...                     ...   
146  146  0.599978  0.600300  0.546678                0.612858   
147  147  0.557894  0.526741  0.479355                0.593299   
148  148  0.562200  0.577547  0.520743                0.606387   
149  149  0.543556  0.532470  0.480622                0.603900   
150  150  0.542303  0.541142  0.485351                0.600427   

     Realized Sales Gross Margin  Cash flow rate  Tax rate (A)  \
0                       0.601457        0.458143      0.000000   
1                       0.610235        0.461867      0.000000   
2                       0.601364        0.458521      0.000000   
3                       0.583541        0.465705      0.000000   
4                       0.598783        0.462746      0.000000   
..                           ...             ...           ...   
146                     0.612909        0.475413      0.096771   
147                     0.593299        0.469685      0.211965   
148                     0.606387        0.473486      0.039174   
149                     0.603900        0.467608      0.150521   
150                     0.600427        0.502562      0.000000   

     Net Value Per Share (B)  Net Value Per Share (A)  ...  \
0                   0.147950                 0.147950  ...   
1                   0.182251                 0.182251  ...   
2                   0.177911                 0.177911  ...   
3                   0.154187                 0.154187  ...   
4                   0.167502                 0.167502  ...   
..                       ...                      ...  ...   
146                 0.191522                 0.191522  ...   
147                 0.180734                 0.180734  ...   
148                 0.180523                 0.180523  ...   
149                 0.181535                 0.181535  ...   
150                 0.180060                 0.180060  ...   

     Current Liability to Assets  Retained Earnings to Total Assets  \
0                       0.147308                           0.903225   
1                       0.056963                           0.931065   
2                       0.098162                           0.909903   
3                       0.098715                           0.906902   
4                       0.110195                           0.913850   
..                           ...                                ...   
146                     0.058174                           0.943531   
147                     0.045002                           0.938042   
148                     0.040820                           0.937403   
149                     0.075828                           0.943052   
150                     0.008564                           0.940513   

     Total expense/Assets  CFO to Assets  Current Liability to Current Assets  \
0                0.064856       0.520382                             0.118250   
1                0.025516       0.567101                             0.047775   
2                0.021387       0.538491                             0.025346   
3                0.024161       0.604105                             0.067250   
4                0.026385       0.578469                             0.047725   
..                    ...            ...                                  ...   
146              0.023093       0.640450                             0.039634   
147              0.011670       0.599367                             0.024026   
148              0.021500       0.610645                             0.017254   
149         

In [20]:
df.describe()

ID      ROA(A)      ROA(B)      ROA(C)  Operating Gross Margin  \
count  151.000000  151.000000  151.000000  151.000000              151.000000   
mean    75.000000    0.543934    0.536486    0.486240                0.607173   
std     43.734045    0.051657    0.051255    0.047263                0.009983   
min      0.000000    0.057185    0.054821    0.066933                0.583541   
25%     37.500000    0.536470    0.527277    0.474918                0.600607   
50%     75.000000    0.550534    0.540661    0.488909                0.604643   
75%    112.500000    0.564681    0.559291    0.508336                0.612170   
max    150.000000    0.607883    0.602870    0.567055                0.637606   

       Realized Sales Gross Margin  Cash flow rate  Tax rate (A)  \
count                   151.000000      151.000000    151.000000   
mean                      0.607171        0.467908      0.124370   
std                       0.009980        0.009682      0.139308   
min                       0.583541        0.454235      0.000000   
25%                       0.600607        0.462603      0.000000   
50%                       0.604643        0.466038      0.086244   
75%                       0.612156        0.470700      0.233424   
max                       0.637606        0.545963      0.642980   

       Net Value Per Share (B)  Net Value Per Share (A)  ...  \
count               151.000000               151.000000  ...   
mean                  0.178009                 0.178010  ...   
std                   0.014310                 0.014315  ...   
min                   0.120012                 0.120012  ...   
25%                   0.172707                 0.172707  ...   
50%                   0.179217                 0.179217  ...   
75%                   0.184295                 0.184295  ...   
max                   0.226244                 0.226244  ...   

       Current Liability to Assets  Retained Earnings to Total Assets  \
count                   151.000000                         151.000000   
mean                      0.073997                           0.932475   
std                       0.042344                           0.015306   
min                       0.008559                           0.841966   
25%                       0.044673                           0.931260   
50%                       0.062649                           0.936348   
75%                       0.095118                           0.940534   
max                       0.252298                           0.957604   

       Total expense/Assets  CFO to Assets  \
count            151.000000     151.000000   
mean               0.031222       0.591471   
std                0.023141       0.034154   
min                0.006373       0.451015   
25%                0.017940       0.572234   
50%                0.024626       0.590522   
75%                0.039783       0.608388   
max                0.203706       0.703654   

       Current Liability to Current Assets  Operating Funds to Liability  \
count                           151.000000                    151.000000   
mean                              0.036957                      0.349907   
std                               0.021842                      0.012709   
min                               0.003688                      0.321583   
25%                               0.019835                      0.342371   
50%                               0.031532                      0.347657   
75%                               0.047342                      0.354611   
max                               0.124883                      0.437756   

       Net Income to Total Assets  Gross Profit to Sales  Equity to Liability  \
count                  151.000000             151.000000           151.000000   
mean                     0.800638               0.607171             0.036466   
std                      0.031231               0.009983             0.018524   
min          

In [21]:
y=df["Bankrupt?"]

In [23]:
X=df.drop(["ID","Bankrupt?"],axis=1)

In [35]:
lr=LogisticRegressionCV(cv=5,max_iter=1000,fit_intercept=False,random_state=42,penalty="l1",solver="saga")
lr.fit(X,y)

C:\Users\soory\.conda\envs\tensorflow\lib\site-packages\sklearn\linear_model\_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
C:\Users\soory\.conda\envs\tensorflow\lib\site-packages\sklearn\linear_model\_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
C:\Users\soory\.conda\envs\tensorflow\lib\site-packages\sklearn\linear_model\_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
C:\Users\soory\.conda\envs\tensorflow\lib\site-packages\sklearn\linear_model\_sag.py:329: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
C:\Users\soory\.conda\envs\tensorflow\lib\site-packages\sklearn\linear_model\_sag.py:329: Conver

LogisticRegressionCV(cv=5, fit_intercept=False, max_iter=1000, penalty='l1',
                     random_state=42, solver='saga')

In [36]:
lr.coef_

array([[  0.        ,  -7.14063717,  -6.06974967,   0.        ,
          0.        ,   0.        ,  -5.1893756 ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  27.05465504,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
        -23.04253709,  15.3445403 ,   0.10749258, -17.26850196,
          0.        ,   4.59652469,   0.        ,   0.        ,
          0.        ,   0.        ]])

In [38]:
df.drop("ID",axis=1).corr()["Bankrupt?"]

ROA(A)                                    -0.475596
ROA(B)                                    -0.504339
ROA(C)                                    -0.507173
Operating Gross Margin                    -0.289790
Realized Sales Gross Margin               -0.289598
Cash flow rate                            -0.248057
Tax rate (A)                              -0.267728
Net Value Per Share (B)                   -0.455005
Net Value Per Share (A)                   -0.454862
Net Value Per Share (C)                   -0.433592
Persistent EPS in the Last Four Seasons   -0.550324
Cash Flow Per Share                       -0.387877
Operating Profit Per Share                -0.401210
Per Share Net profit before tax           -0.536094
Debt ratio %                               0.547993
Net worth/Assets                          -0.547993
Operating profit/Paid-in capital          -0.400195
Net profit before tax/Paid-in capital     -0.533071
Operating profit per person               -0.319755
Working Capi

In [48]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score

In [50]:
dt=DecisionTreeClassifier()

In [51]:
dt.fit(X,y)
pred=dt.predict(X)
print(f1_score(y,pred))

1.0


In [52]:
rf=RandomForestClassifier()
rf.fit(X,y)

RandomForestClassifier()

In [53]:
pred=rf.predict(X)
print(f1_score(y,pred))

1.0


In [91]:
dt.feature_importances_

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05243056, 0.        , 0.        ,
       0.        , 0.        , 0.19690586, 0.        , 0.        ,
       0.        , 0.04660494, 0.        , 0.        , 0.        ,
       0.094375  , 0.        , 0.47700187, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.13268177])

In [89]:
weights=np.array(rf.feature_importances_)

In [86]:
val=np.array(df.drop(["ID","Bankrupt?"],axis=1).iloc[1,:].values)

In [57]:
df.columns

Index(['ID', 'ROA(A)', 'ROA(B)', 'ROA(C)', 'Operating Gross Margin',
       'Realized Sales Gross Margin', 'Cash flow rate', 'Tax rate (A)',
       'Net Value Per Share (B)', 'Net Value Per Share (A)',
       'Net Value Per Share (C)', 'Persistent EPS in the Last Four Seasons',
       'Cash Flow Per Share', 'Operating Profit Per Share',
       'Per Share Net profit before tax', 'Debt ratio %', 'Net worth/Assets',
       'Operating profit/Paid-in capital',
       'Net profit before tax/Paid-in capital', 'Operating profit per person',
       'Working Capital to Total Assets', 'Cash/Total Assets',
       'Current Liability to Assets', 'Retained Earnings to Total Assets',
       'Total expense/Assets', 'CFO to Assets',
       'Current Liability to Current Assets', 'Operating Funds to Liability',
       'Net Income to Total Assets', 'Gross Profit to Sales',
       'Equity to Liability', 'Bankrupt?'],
      dtype='object')

In [78]:
val.shape

(1, 30)

In [75]:
weights.shape

(30,)

In [90]:
np.matmul(val,weights)

0.3873479039178709

In [80]:
weights.mul(val)

AttributeError: 'numpy.ndarray' object has no attribute 'mul'

In [64]:
lrr=LinearRegression(fit_intercept=False)

In [65]:
lrr.fit(X,y)

LinearRegression(fit_intercept=False, normalize=True)

In [66]:
lrr.coef_

array([ 1.97812347e+00, -3.08451527e+00,  1.83578396e+00, -1.07014550e+04,
       -1.12749697e+02,  3.43532915e+00,  1.09013080e-01, -3.43486631e+02,
        3.30087458e+02,  1.69438986e+01, -2.58417123e+00, -1.34422124e+01,
        6.08963388e+00, -1.81863810e+01,  6.19284344e+00,  4.39183348e+00,
       -8.55758709e+00,  1.56459116e+01, -2.12078731e+00,  1.85880870e+00,
       -7.24840838e-01,  8.27431404e-01, -1.28621410e+00,  1.04392460e+00,
        6.90944938e-01,  7.77862228e+00,  4.77244714e+00,  5.16469588e-01,
        1.08080249e+04,  1.13403843e+00])

In [93]:
df2=pd.read_csv("Telecome Users KTDK-1 - Telecome Users.csv")

In [99]:
from sklearn.preprocessing import LabelEncoder

In [98]:
df2

ID  Gender  SeniorCitizen Married  Tenure PhoneService MultipleLines  \
0      0  Female              0     Yes       1           No            No   
1      1    Male              0      No      34          Yes            No   
2      2    Male              0      No       2          Yes            No   
3      3    Male              0      No      45           No            No   
4      4  Female              0      No       2          Yes            No   
..   ...     ...            ...     ...     ...          ...           ...   
121  121  Female              0     Yes      65          Yes           Yes   
122  122    Male              0      No       3          Yes            No   
123  123    Male              0      No       1          Yes            No   
124  124    Male              0      No      30          Yes            No   
125  125    Male              0     Yes      15          Yes            No   

    InternetService TechSupport StreamingTV StreamingMovies        Contract  \
0               DSL          No          No              No  Month-to-month   
1               DSL          No          No              No        One year   
2               DSL          No          No              No  Month-to-month   
3               DSL         Yes          No              No        One year   
4       Fiber optic          No          No              No  Month-to-month   
..              ...         ...         ...             ...             ...   
121     Fiber optic         Yes         Yes              No        Two year   
122              No          No          No              No        One year   
123             DSL          No          No              No  Month-to-month   
124             DSL          No         Yes              No        One year   
125             DSL         Yes          No             Yes  Month-to-month   

    PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  \
0                Yes           Electronic check           29.85         29.85   
1                 No               Mailed check           56.95       1889.50   
2                Yes               Mailed check           53.85        108.15   
3                 No  Bank transfer (automatic)           42.30       1840.75   
4                Yes           Electronic check           70.70        151.65   
..               ...                        ...             ...           ...   
121              Yes    Credit card (automatic)           99.05       6416.70   
122               No               Mailed check           19.60         61.35   
123              Yes           Electronic check           45.65         45.65   
124               No    Credit card (automatic)           64.50       1929.95   
125              Yes               Mailed check           69.50       1071.40   

    Churn  
0      No  
1      No  
2     Yes  
3      No  
4     Yes  
..    ...  
121    No  
122    No  
123   Yes  
124    No  
125    No  

[126 rows x 17 columns]

In [101]:
for i in df2.select_dtypes("object"):
    lb=LabelEncoder()
    df2[i]=lb.fit_transform(df2[i])

In [102]:
X=df2.drop(["ID","Churn"],axis=1)
y=df2.Churn

In [103]:
dt2=DecisionTreeClassifier()
dt2.fit(X,y)

DecisionTreeClassifier()

In [104]:
dt2.feature_importances_

array([0.05605848, 0.        , 0.00684262, 0.07254984, 0.        ,
       0.        , 0.        , 0.05913978, 0.        , 0.02052786,
       0.28283125, 0.11123114, 0.        , 0.22413237, 0.16668666])

In [105]:
X.columns

Index(['Gender', 'SeniorCitizen', 'Married', 'Tenure', 'PhoneService',
       'MultipleLines', 'InternetService', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')